### ISSUE TITLE
Pizza details page in React

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/inspiring-pizza-fe#1]
This project needs pizza details page. You are free to make any design.

**Comment by izekkimohamed** [comment]
hello i just forked your code i want to ask if you want to switch to nextjs instead of plain react?

**Comment by DamyanBG** [comment]
> hello i just forked your code i want to ask if you want to switch to nextjs instead of plain react?
> 
> 

Why to switch to NextJS?

**Comment by MehekFatima** [comment]
Hi @DamyanBG , I'd like to contribute by designing and implementing the Pizza Details page.

**Comment by DamyanBG** [comment]
> Hi @DamyanBG , I'd like to contribute by designing and implementing the Pizza Details page.

I am glad that you want to contribute. I will wait for your PR!

**Comment by MehekFatima** [comment]
Just wanted to mention that the issue #2  has been resolved with the merged PR. If it looks good to you, could you please close the issue? @DamyanBG

**Comment by DamyanBG** [comment]
I like it, thank you!
